version: 2.1
orbs:
  node: circleci/node@7.0.0
jobs:
  build:
    docker:
      - image: node:20
    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare pnpm@latest-9 --activate
            pnpm config set store-dir .pnpm-store
      - run:
          name: Install Dependencies
          command: |
            pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - .pnpm-store
      - run:
          command: pnpm run build
          name: Build app
workflows:
  build-and-test:
    jobs:
      - build:
        filters:
          branches: 
            only: 
              -main
