version: 2.1
orbs:
  node: circleci/node@7.0.0
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: pnpm
      - run:
          command: pnpm run build
          name: Build app
workflows:
  build-and-test:
    jobs:
      - build:
        filters:
          branches: 
            only: 
              -main
