version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: node_modules/@angular/cli/bin/ng.js build --configuration production --build-optimizer --output-hashing=none
workflows:
  build-and-test:
    jobs:
      - build:
        filters:
          branches: 
            only: 
              -master
